DHAN_AUTH_BASE_URL = "https://auth.dhan.co"
DHAN_API_BASE_URL = "https://api.dhan.co"

AUTH_RATE_LIMIT_MAX = 5
AUTH_RATE_LIMIT_WINDOW = 60
GENERAL_RATE_LIMIT_MAX = 60
GENERAL_RATE_LIMIT_WINDOW = 60

SESSION_CHECK_BUFFER_MINUTES = 5
